# --- Website Basics --- #
title: Ayume Milagres
author: Ayume Milagres
tagline: Data Analyst | Engineer | Curious Problem-Solver

# --- Navigation Bar --- #
navbar-links:
  About Me: "aboutme"
  Projects: "projects"
  Contact: "contact"

# --- Profile Avatar --- #
avatar: "/assets/img/avatar-icon.png"
round-avatar: true

# --- Social Links in Footer --- #
social-network-links:
  email: "ayumilagres@gmail.com"
  github: "ayumilagres"
  linkedin: "your-linkedin-username"  # Replace with your actual LinkedIn username

# --- SEO and Sharing --- #
rss-description: Portfolio site for Ayume Milagres
share-links-active:
  twitter: false
  facebook: false
  linkedin: true
url-pretty: "ayumilagres.github.io"

# --- Display Settings --- #
title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: true

# --- Site Colors --- #
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# --- Date Format --- #
date_format: "%B %-d, %Y"

# --- Jekyll & Plugins --- #
timezone: "America/Sao_Paulo"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5
plugins:
  - jekyll-paginate
  - jekyll-sitemap

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
